import {
  Library,
  Waves,
  Volleyball,
  Goal,
  Utensils,
  Presentation,
  Moon,
  CircleDot,
  Building2,
  Trophy,
  HeartPulse,
  Camera,
  Bus,
  FlaskConical,
  Dumbbell,
  Gamepad2,
  Users,
  BookOpen,
  Briefcase,
  Leaf,
  CreditCard,
  CheckCircle2,
  type LucideIcon,
} from 'lucide-react'

const ICON_BY_LABEL: Record<string, LucideIcon> = {
  library: Library,
  'swimming pool': Waves,
  'basketball court': Volleyball,
  'football field': Goal,
  cafeteria: Utensils,
  auditorium: Presentation,
  'prayer room': Moon,
  'tennis court': CircleDot,
  'student housing': Building2,
  'padel court': Trophy,
  'medical room': HeartPulse,
  atm: CreditCard,
  'cctv secure': Camera,
  'shuttle service': Bus,
  laboratory: FlaskConical,
  gym: Dumbbell,
  'recreational zones': Gamepad2,
  'clubs and community': Users,
  'clubs & community': Users,
  'study rooms': BookOpen,
  'careers team': Briefcase,
  'green spaces': Leaf,
}

export function getInclusionIcon(label: string): LucideIcon {
  return ICON_BY_LABEL[label.trim().toLowerCase()] || CheckCircle2
}
